services:
  web:
    build: .
    # image: ashish1106/bopo:v2
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 bsafe.asgi:application"
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/app 
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
